#!/usr/bin/env php
<?php
declare(strict_types=1);

use Modulith\ArchCheck\CLI\Application;

if (!defined('ARCHCHECK_COMPOSER_INSTALL')) {
    foreach (array(__DIR__ . '/../../../autoload.php', __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
        if (file_exists($file)) {
            define('ARCHCHECK_COMPOSER_INSTALL', $file);

            break;
        }
    }
}

unset($file);

if (!defined('ARCHCHECK_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require ARCHCHECK_COMPOSER_INSTALL;

$application = new Application();

$application->run();
